// URLs 
:url-testnet-fedstats: https://fedstats.veriscope.network/

= Troubleshooting
:navtitle: Troubleshooting

== Node Installation

=== 1) Has your trust anchor account been set in .env (veriscope_ta_node/.env)?

Trust anchor accounts are managed by the http-api.js script which loads it from .env. Ensure you have the trust anchor account (TRUST_ANCHOR_ACCOUNT) and private key (TRUST_ANCHOR_PK) set. If you plan to manage multiple accounts for testing purposes, you can swap these accounts in .env and restart ta-node-1 as follows:

----
sudo systemctl restart ta-node-1
----

[IMPORTANT]
Do not include "0x" prefix in TRUST_ANCHOR_PK

// TODO Below is an example of a completed account setup in .env:

// ----
// TRUST_ANCHOR_PK=ae21....ce00
// TRUST_ANCHOR_PREFNAME="vs-....-1"
// TRUST_ANCHOR_ACCOUNT=0xB158....b39
// WEBHOOK_CLIENT_SECRET=tho....uain
// ----

=== 2) Is your trust anchor account loaded in the web-app the same as in veriscope_ta_node/.env?

When running Step 2 of the installation script (Nethermind), the trust anchor account in .env is overwritten. By refreshing the *Load TA Account* in the web-app, your trust anchor account in the veriscope_ta_node/.env will be loaded in the web-app.

=== 3) Is Nethermind running? Is your Nethermind node in fedstats? Has it completed syncing?

In order to receive blockchain events or post transactions, your nethermind client must be running. You can confirm this by

* Viewing {url-testnet-fedstats}[fedstats.veriscope.network^] to see if your node is up and synchronized.
* Running the following command in the console:

----
sudo systemctl status nethermind
 ● nethermind.service - Nethermind Ethereum Daemon
      Loaded: loaded (/etc/systemd/system/nethermind.service; disabled; vendor p>
      Active: active (running) since Thu 2021-11-25 21:25:19 UTC; 1 weeks 0 days>
    Main PID: 1419555 (Nethermind.Runn)
       Tasks: 72 (limit: 4631)
      Memory: 1.2G
      CGroup: /system.slice/nethermind.service
              └─1419555 /opt/nm/Nethermind.Runner -c /opt/nm/config.cfg

 Dec 03 19:59:50 pcf Nethermind.Runner[1419555]: eth_blockNumber          >
 Dec 03 19:59:50 pcf Nethermind.Runner[1419555]: eth_chainId              >
 Dec 03 19:59:50 pcf Nethermind.Runner[1419555]: eth_getLogs              >
 Dec 03 19:59:50 pcf Nethermind.Runner[1419555]: ------------------------->
 Dec 03 19:59:50 pcf Nethermind.Runner[1419555]: TOTAL                    >
 Dec 03 19:59:50 pcf Nethermind.Runner[1419555]: ------------------------->
 Dec 03 19:59:50 pcf Nethermind.Runner[1419555]:
 Dec 03 19:59:50 pcf Nethermind.Runner[1419555]: 2021-12-03 19:59:50.0323|>
 Dec 03 19:59:54 pcf Nethermind.Runner[1419555]: 2021-12-03 19:59:54.0361|>
 Dec 03 19:59:54 pcf Nethermind.Runner[1419555]: 2021-12-03 19:59:54.0361|>
 Dec 03 19:59:58 pcf Nethermind.Runner[1419555]: 2021-12-03 19:59:58.0401|>
 Dec 03 19:59:58 pcf Nethermind.Runner[1419555]: 2021-
----

The service should show as Active.

To confirm the web-app, http-api and Nethermind (fully synched) are all connected, you should be able to fetch account balance in the web-app.

=== 4) Logging

Both the web-app and NodeJS logs to files in the following directories:

*webapp \-> /opt/veriscope/veriscope_ta_dashboard/storage/logs*
----
$ pwd
/opt/veriscope/veriscope_ta_dashboard/storage/logs
$ ls
laravel.log
----

*nodejs \-> /opt/veriscope/veriscope_ta_node/logs*
----
$ pwd
/opt/veriscope/veriscope_ta_node/logs
$ ls
blockchain-data.combined.log  http-api.error.log
blockchain-data.error.log     shyft-template-helper.combined.log
http-api.combined.log         shyft-template-helper.error.log
----

=== 5) 503 when loading blockchain data

If loading any of the blockchain data like so (see below section):

----
$ node -e 'require("./blockchain-data").getAllAttestations()'
----

...you may notice 503 errors in the logs. 503 is returned when the WEBHOOK_CLIENT_SECRET in both .env files may not be set.
If you need to recreate the secret you can run this step from the guide:

----
10) Regenerate webhook secret
----

This will overwrite WEBHOOK_CLIENT_SECRET in both .env files for veriscope_ta_dashboard and veriscope_ta_node.


---
//TODO

// How do I verify a new Trust Anchor account?

// How do I know that my Node is fully synched and not missing data?

// I'm missing some attestations

// I'm missing some key-value pairs

// I'm missing some verified Trust Anchors

// Post set-up steps: Get all data!
// https://github.com/Paycase/veriscope/tree/state-machine#load-blockchain-data

// Is Nethermind running?
// https://github.com/Paycase/veriscope/tree/state-machine#3---is-nethermind-running-is-your-nethermind-node-in-the-fedstats-has-it-completed-the-sync