---
- name: Prepare ansible controller (localhost)
  hosts: localhost
  gather_facts: false
  vars:
    ansible_host: localhost
  tasks:

  - name: Delete veriscope code archive
    ansible.builtin.file:
      path: "{{ controller_working_dir }}/veriscope.tar.gz"
      state: absent

  - name: Archive (package) veriscope code
    community.general.archive:
      path: "{{ controller_working_dir }}/*"
      dest: "{{ controller_working_dir }}/veriscope.tar.gz"
      exclude_path:
        - "{{ controller_working_dir }}/infra"
        - "{{ controller_working_dir }}/.git"
        - "{{ controller_working_dir }}/.github"
      format: gz
      force_archive: true

  - name: Install python3 pip
    ansible.builtin.package:
      name:
        - python3-pip
        - python3-setuptools

  - name: pip3 self-update
    pip:
      name: pip
      executable: pip3
      state: latest

  - name: Install python requirements for ansible
    ansible.builtin.pip:
      name: boto3>1.24.0,<1.25.0
      executable: pip3
