---
- name: Update Trust Anchor accounts and keys
  hosts: web

  tasks:

    - name: Check inputs - Update TA accounts and keys
      ansible.builtin.assert:
        that:
          - trust_anchors is defined and trust_anchors is iterable and trust_anchors | length > 0
          - trust_anchors | map(attribute='private_key') | list | length == trust_anchors | length
          - trust_anchors | map(attribute='address') | list | length == trust_anchors | length
          - trust_anchors | map(attribute='preferred_name') | list | length == trust_anchors | length
        success_msg: Required inputs provided. Proceeding to copy chain artifacts and setup nodejs app.
        fail_msg: Required inputs not provided. Please provide required values and try again.
    
    - name: Stop required services - Update TA API config
      ansible.builtin.service:
        name: "{{ item }}"
        state: stopped
      ignore_errors: false
      become: true
      with_items:
        - ta-node-1

    - name: Generate list of TA account details - Install TA API
      ansible.builtin.import_tasks: ../tasks/generate-ta-details-lists.yaml

    - name: Validate TA account details - Install TA API
      ansible.builtin.import_tasks: ../tasks/validate-input-ta-account-details.yaml

    - name: Update Trust Anchor pk, account, prefname
      ansible.builtin.blockinfile:
        path: "{{ api_config_path }}"
        backup: true
        block: |
          TRUST_ANCHOR_PK={{ private_keys_csv }}
          TRUST_ANCHOR_ACCOUNT={{ addresses_csv }}
          TRUST_ANCHOR_PREFNAME={{ preferred_names_csv }}
        marker: "# {mark} AUTOMATION MANAGED BLOCK TA ACCOUNT INFO"
        state: present
        owner: veris
        group: veris

    - name: Start TA API services - Update TA API config
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
      ignore_errors: false
      become: true
      with_items:
        - ta-node-1

- name: Restart nethermind service
  hosts: nethermind

  tasks:
    - name: Restart nethermind service
      ansible.builtin.import_tasks: ../tasks/restart-services.yaml
      vars:
        services:
          - "{{ veriscope_nm_services }}"