= Federated Coalitions
:navtitle: Coalitions

Federated Coalitions
A Federated Coalition ('Syndicate', Strong Federation, or otherwise) is a set of independent operators that bind themselves to similar (or even equivalent) requirements (usually as a result of this, they have aligned incentives, or if not legal obligations). Under most conditions these actors require explicit trust guarantees with one another - without them, there are increasing costs (if not inability) to operate effectively.

By nature, the benefits of working within this system far outweigh the benefits of acting independently or nefariously. Federated coalitions on Shyft Network can be bound to regulatorily-enforced rule sets, and some are even used by government entities to enforce regulations.

An example of a Shyft Network federated coalition across the Veriscope Network:
A group of VASPs committed to determining, standardizing, and enforcing policies by way of trusted smart contracts, with opt-in input from local regulatory bodies, inspired on FATF recommendations, and adopted by qualifying industry participants.

Another example of a federated coalition across Veriscope:
Actors consenting (within a GDPR-compliant consent-registry framework) to “attestations” that have been placed on these public addresses by a Trust Anchor, which initiates a process that maps the Trust Channels in totality to the user’s accounts across the Federated Coalition. As a result, the transfer of assets from one actor to another has a complete provable history trail with all parties mapped and validated, while ensuring all regulatory requirements are met, and all information is transmitted and delivered privately between only the coalition of VASPs that were required in the process as set out by the rules on the Trust Channel.

Creating a Coalition
Coalitions are composed of VASPs whose users frequently transact with each other. As an example, for the Travel Rule, these exchanges now need to frequently share user identity data about the originator and beneficiary involved in transactions. Coalitions will collaboratively define standards around inter- and intra-coalition information sharing, business activities, and communication in the context of relevant global and local regulatory and jurisdictional requirements.

Creating and managing an administrator or group of admins:

Setting a primary admin
Promote an admin
Setting up the coalitions consensus voting rights for confirmation proposals
Revoke administrator
Coalition Proposals
Confirmation threshold to enable a proposal to change admins in a coalition
Viewing the admin confirmation threshold for a given coalition
Changing the current amount of admins in a coalition required in a Confirmation threshold
Request access as an admin
