= Shyft Identity and KYC Contract Suite
:navtitle: KYC

The smart contract suite ensures that the standardization of data transmitted on behalf of the service provider (Trust Anchor) and sending party (customer) are in-line with the jurisdictional requirements required for transmission.

This is completed through a set of contract standards that define information requirements, data and asset transit flows, conditionals formatting abilities, jurisdictional information, coalition information standards, trust anchor information, and more.

The Identity contracts outline a rule set by how broad data fields can be passed data, and therefore provides a universal binding standard for how all VASPs, current and future, will send and receive each other's datasets.

Public Ledger and Transaction Handling
The Identity and KYC contract suites also contain cryptographic attestation libraries to enable confidential transactions to be created for public network visible transmissions, using Merkle Tree base proofs, Merkle Patricia Trie proofs. These transactions are fully transparent to the sending and receiving VASPs for compliance reasons, but are confidentialised across the public network to ensure GDPR and privacy is not violated across global transactions.

The integrity of the public ledger is critical in ensuring audit trails of actions being done on user information are secured and immutable both for historical record keeping reasons and also to ensure that, in the event that VASPs in the digital asset space cease to exist, the participants involved in the transactions still maintain historical linkage and anchoring trails. As a result, we can mitigate against the risk of VASPs becoming single points of failure.

Since the digital asset space is not regulated in the same way as the banking system is, we need to ensure that all audit trails are immutable and indelible by maintaining an open standard for how the many types of ecosystem participants interact, including: exchanges, dapps, regulators, public permissionless blockchains, permissioned networks and more.
