import { getField, updateField } from 'vuex-map-fields';
import { actions } from './actions';
import { mutations } from './mutations';
import { getters } from './getters';

export default {
    state: {
        attestationsSocketId: null,
        form: {
            ta_prefname: '',
            ta_password: '',
            ta_jurisdiction: '',
            ta_token_amount: 0,
            user_prefname: '',
            user_password: '',
            attestation_user: '',
            attestation_user_account: '',
            user_coin_blockchain: '',
            user_coin_token: '',
            user_coin_address: '',
            user_coin_memo: '',
            attestation_document_matrix: '',
            attestation_effective_date: null,
            attestation_expiry_date: '',
            attestation_public_data: '',
            attestation_wallet_address: '',
            attestation_availability_address: '',
            attestation_jurisdiction: '',
            attestation_kyc_data: null,
            attestation_effective_date: null,
            attestation_ta_account: '',
            ta_user_address: '',
            ta_attestation_hash: '',
            attestation_hash: '',
            user_crypto_address: '',
            ta_new_admin_account: '',
            ta_vasp_address: '',
            ta_vasp_prefname: '',
            user_crypto_address_type: '',
            dob: null,
            gender: null,
            ta_unique_account: '',
            ta_key_name: '',
            ta_key_value: '',
            ivms_legal_person_name: '',
            ivms_legal_person_name_identifier_type: '',
            ivms_address_type: '',
            ivms_street_name: '',
            ivms_building_number: '',
            ivms_building_name: '',
            ivms_postcode: '',
            ivms_town_name: '',
            ivms_country_sub_division: '',
            ivms_country: '',
            ivms_department: '',
            ivms_sub_department: '',
            ivms_floor: '',
            ivms_room: '',
            ivms_town_location_name: '',
            ivms_district_name: '',
            ivms_address_line: '',
            ivms_postbox: '',
            ivms_customer_identification: '',
            ivms_national_identifier: '',
            ivms_national_identifier_type: '',
            ivms_country_of_registration: '',
  
        },
        genderData: [
            {label: 'Male', value: 'male'},
            {label: 'Female', value: 'female'}
        ],
        getTasData: [],
        taGetDiscoveryLayerKeysData: [],
        getTaUsersData: [],
        taCountryData: [],
        taWalletTypeData: [],
        taWalletAddressData: [],
        completedRoutes: [],
        currentRoute: '',

        ta_user_accounts: [],
        ta_temp_user: '',
        taSetAttestationTypeOptions: [{id:0, type:"KYC"},
                                    {id:1, type:"WALLET"},
                                    {id:2, type:"TRANSACTION"}],
        ta_accounts: [],
        ta_temp_account: '',
        taIsVerifiedData: 'Is TA Verified Result:',
        updatedIvmsData: 'IVMS Updated Data Result:',
        taAddToChannelData: null,
        taAddToChannelOptions: ["0 not a trust channel administrator",
                                        "1 requires more administrator votes",
                                        "2 trust channel not active",
                                        "3 trust anchor already within mapping",
                                        "4 could not setup",
                                        "5 trust anchor added to trust channel"],

        taSetUniqueAddressData: null,
        taSetUniqueAddressOptions: ["0 = not administrator",
                                    "1 = TA Unique address set"],
        taGetUniqueAddressData: null,

        taSetupEventsData: [],
        taEventData: [],
        taGetIndex: '',
        taSetJurisdiction: '',
        taGetJurisdiction: '',
        taCreateUserData: null,
        taSetKycAttestationHashData: '',
        taSetKycAttestationData: 0,
        taSetKycAttestationError: null,
        taSetKycAttestationOptions: ["", "Please Wait....",
                                        "Trust anchor is not verified",
                                        "Attestation not valid",
                                        "Attestation already exists",
                                        "Attestation set"],
        taSetWalletAttestationHashData: '',
        taSetWalletAttestationData: 0,
        taSetWalletAttestationError: null,
        taSetWalletAttestationOptions: ["", "Please Wait....",
                                        "Trust anchor is not verified",
                                        "Attestation not valid",
                                        "Attestation already exists",
                                        "Attestation set"],
        taGetBalanceData: '0 SHFT',
        taGetUserAttestationsData: [],
        taGetAttestationComponentsData: [],

        taGetAssociationData: [],
        taAssignCryptoAddressData: '',
        taGetUserWalletAddressData: [],
        taCreateCoalitionData: '',
        taRegisterJurisdictionData: '',
        taRegisterJurisdictionOptions: ["0 not verified",
                                        "1 jurisdiction already set, now waiting for approval",
                                        "2 trust anchor jurisdiction has been set up first time"],
        taRequestCoalitionData: '',
        taAddAdminCoalitionData: '',
        taGetAllAttestationsData: [],
        showFatfButton: 'none',
        showTaCreateAccount: 'none',
        showTaCreateAccountGreenMark: 'none',
        showTaCreateAccountErrorMark: 'none',
        showTaIsVerifiedData: 'none',
        showTaIsVerifiedDataGreenMark: 'none',
        showTaIsVerifiedDataErrorMark: 'none',
        showUpdatedIvmsData: 'none',
        showUpdatedIvmsDataGreenMark: 'none',
        showUpdatedIvmsDataErrorMark: 'none',
        showKeyValuePairResult: 'none',
        showKeyValuePairResultGreenMark: 'none',
        showKeyValuePairResultErrorMark: 'none',
        showTaGetBalanceResult: 'none',
        showTaGetBalanceResultGreenMark: 'none',
        showTaGetBalanceResultErrorMark: 'none',
        showTaCreateUserResult: 'none',
        showTaSetKycAttestationResult: 'none',
        showTaSetKycAttestationHash: 'none',
        showTaSetKycAttestationError: 'none',
        showTaSetWalletAttestationResult: 'none',
        showTaSetWalletAttestationHash: 'none',
        showTaSetWalletAttestationError: 'none',
        taSetKeyValuePairData: '',
        showExportIVMSFailedData: 'none',
        exportIVMSFailedData: 'none',

    },
    getters: {
        // getField,
        ...getters
    },
    actions,
    mutations: {
        updateField,
        ...mutations
    },
}
