= Step 6. End-to-end testing with the Veriscope team and other VASPs
:navtitle: 6) Test with other VASPs

At this point, your VASP should be able to:

* a) Post attestations (i.e. an intent to withdraw funds to a particular address)
* b) Listen & respond to attestations on relevant (deposit) addresses
* c) Initate & share data peer-to-peer between VASPs

== a) Post attestations for crypto withdrawal requests
As per the FATF requirement, VASPs that initiate crypto withdrawals must make best efforts to identify the destination for the crypto transaction. If the destination is another VASP, both VASPs must coordinate the transfer of both originator and beneficiary KYC data.

The identification of counterparties can be established via attestation transactions on the Shyft Network.

VASPs that are withdrawing crypto from their platform set attestations on the network.

For this step, VASPs are required to set attestations for each unique withdrawal crypto address requested by their users on their platform.

== b) Subscribe to events
Due to the nature of blockchains processing transactions, relay nodes can subscribe to specific events such as attestations.

Attestations are the key element to identifying VASPs that are connected via crypto transactions between their respective platforms. They include key information to identify who is the originator VASP, who is the user on that platform, and what crypto transaction originated from the platform.

In this step, VASPs must be able to subscribe to these events and respond to attestation requests.

== c) Respond to and share data with your peers
The final step in this milestone is to complete the cycle, i.e. transferring and receiving KYC data.

It is important to note here that originator or beneficiary KYC data is not recorded on the Shyft Network blockchain. The transfer of the KYC data is done directly with the counterparty VASP over standard HTTPS API.  

Therefore your VASP platform must expose a FATF KYC endpoint whereby it can respond to requests for KYC data or make such requests to a counterparty. See here for more information.

The completion of this step means that a VASP is eligible for travel rule data transmission.