= Step 4a: Log-in to the Veriscope web-app and complete your VASP profile (i.e. IVMS data)
:navtitle: 4-a) Complete Profile

Once the Node installation is complete and the trust anchor account verified, a VASP representative (admin user) should log-in to the Veriscope dashboard and complete the VASP profile / IVMS data. This information is not posted to or stored on the Shyft Network. It will, however, be included in the IVMS template that's shared with other VASPs when exchanging KYC data peer-to-peer.

[NOTE]
====
The interVASP Messaging Standard (IVMS) is a standard put forth by industry members in order to standardize what KYC data should be gathered and formatted for the FATF Travel Rule.

The pdf download available from https://intervasp.org/[intervasp.org] documents what information must be included when sharing KYC data between counterparties; user KYC and platform KYB.
====

[NOTE]
The dashboard url (i.e. Node http url) and admin user login credentials were generated during the Node installation step.