- name: Check if the secret is in the desired format
  block:
    - name: Print secrets when debug is true
      debug:
        msg: "{{ secret_data }}"
      when: debug is true

    - name: Check if secret is in JSON format
      set_fact:
        format_match: "{{ secret_data is mapping }}"
      when: expected_format | lower == 'json'
      ignore_errors: true

    - name: Check if the secret is in key-value format
      set_fact:
        is_key_value_format: "{{ secret_data is mapping and secret_data is not string }}"
      when: expected_format | lower == 'kvp'
      ignore_errors: true

    - name: Check if secret is in string format
      set_fact:
        format_match: "{{ secret_data is string }}"
      when: expected_format | lower == 'string'
      ignore_errors: true

    - name: Throw error if format does not match the expected format
      fail:
        msg: "The secret is not in the expected {{ expected_format }} format!"
      when: not format_match
  vars:
    format_match: false
  rescue:
    - name: Print error details
      debug:
        msg: "An error occurred: {{ ansible_failed_result.msg }}"

    - fail:
        msg: "An error occurred while checking the secret format. Details: {{ ansible_failed_result.msg }}"
