---
- name: Fetch secrets from GCP Secret Manager
  gcp_secret_manager_secret_version_facts:
    secret: "{{ ta_dashboard_db_cluster_secret_name }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_auth_kind }}"
    service_account_file: "{{ gcp_service_account_file }}"
  register: fetched_secrets

- name: Check secret format
  include_tasks: check_secret_format.yml
  vars:
    secret_data: "{{ fetched_secrets['secrets'][0]['payload']['data'] }}"

- name: Set facts from GCP secrets
  set_fact:
    pgsql_cltr_host: "{{ fetched_secrets['secrets'][0]['payload']['data']['cluster_endpoint'] }}"
    pgsql_cltr_port: "{{ fetched_secrets['secrets'][0]['payload']['data']['cluster_port'] }}"
    # Map other secrets similarly
