---
# Set common facts
- name: Set common facts
  set_fact:
    ta_db_name: "trustanchor-{{ inventory_hostname_short }}"
    ta_db_user: "trustanchor-{{ inventory_hostname_short }}"

- name: Extract secrets based on secret manager type
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "{{ secret_manager_type }}.yml"
      paths:
        - tasks/
