
= Governance Task Force
:navtitle: Task Force

This section contains the Terms of Reference for the Governance Task Force of the VERISCOPE Onboarding Verification model.

== Role of the Governance Task Force
The Governance Task Force has the responsibility for defining and maintaining the Rules Framework - i.e. the policies and processes outlining what information VASPs must provide at onboarding, and the rules of engagement related to VASPs verifying one another’s information held on the Discovery Layer. The Task Force effectively acts as the design authority for the Rules Framework.

Through the design of the Rules Framework, the Governance Task Force aims to:

* Promote trust and transparency between participants on the network;
* Foster verification of VASPs on the network and design processes that facilitate trust and transparency between VASP participants on the network in a safe and secure way;
* Monitor and maintain the defined processes to respond to evolving policies, regulatory requirements and/or standards as applicable;
* Act as a liaison for VASPs to raise questions and propose changes to the verification methodology as required on an ongoing basis;
* Act as a decision-making authority for changes to policies and procedures related to the Rules Framework; and
* Act as the kickstarter for the Rules Framework which the VASPs can begin to utilize.
* It is anticipated that over time, the VASP participants will become more autonomous in terms of their interactions with counter-parties, and their requirements of each other relating to information presented on the Discovery Layer, but the Governance Task * Force is the group which lays the initial foundations from which the VASPs can build over time and oversees and approves changes as needed, including to this Terms of Reference.

== Composition of the Task Force
The Task Force consists of representation from the following key stakeholder groups:

* Key VASP participants, including representation across the geographic footprint of Shyft’s network participants as well from larger and smaller participating VASPs;
* Subject matter expert/Advisor representation in the areas of compliance and AML; and
* Infrastructure and technology representation.

As of September 2020, the initial representatives of the Governance Task Force are (listed alphabetically):

* Aave
* Binance
* Bitfinex
* Bitmex
* Bitsonic
* CoinHako
* Genesis block
* HashKey Pro
* Hodlnaut
* Huobi
* Local Bitcoins
* OKex
* Paycase Financial
* Tether
* TokoCrypto
* Unocoin

[NOTE]
====
The Task Force is chaired by Rick McDonell (Shyft Advisor) and Josée Nadeau (Shyft Advisor).

Shyft is acting as the Secretariat of the Task Force.

The Task Force may have up to 30 participants, in addition to the Chairs.
====

At this juncture, there are no set terms for representatives to stay on the Task Force. However, it is envisaged that some rotations and changes in the representation should be considered in due time as the composition of the VASP participants evolves and grows over time, with a view to maintaining a balanced representation (e.g., consider whether more structured regional representation is needed, regional consultative sub-groups or working groups on specific topics).

== Communication
The Task Force will maintain regular contact at least on a monthly basis by emails or other medium and via virtual meetings when needed.

== Decision-making and reporting
The Task Force will aim to make decisions on a consensus basis, seeking compromises acceptable to all representatives through effective dialogue. In the rare event of an absence of consensus, the Chairs will make a final determination in consultation with Shyft.

* Decisions can be made during meetings or in writing on a non-objection basis.
* Decisions at meetings require a quorum of 2/3 of the Task Force representatives.
* Any decisions by the Task Force related to changes to the Terms of Reference and/or the Rules Framework will be recorded in writing.
* The Chatham House rule will apply to the discussion and decision.
* Documents approved by the Task Force will be provided to all VASP participants on a timely basis.