= How to onboard to Veriscope as a VASP
:navtitle: Get Started

There are several steps a VASP needs to complete to onboard to Veriscope and to meet their Travel Rule obligations. These are outlined below.

== VASP Onboarding Steps

_Potential owners are indicated in `*[...]*`._

====
. Review & sign Veriscope agreements `*[Compliance, Legal]*`
. Install & run a Node `*[Engineering]*`
. Create a VASP account (aka Trust Anchor account) and request it to be verified & onboarded `*[Engineering]*`
. Log-in to the Veriscope web-app and: 
.. Complete your VASP profile (i.e. IVMS data) `*[Compliance]*`
.. Register Discovery Layer data on-chain so that your VASP is discoverable `*[Compliance]*`
. Implement the Veriscope APIs and related business logic `*[Engineering]*`
. Test the end-to-end flow `*[Engineering, Compliance, Operations, Support]*`
. Request to be onboarded to mainnet `*[Engineering, Compliance]*`
====

Once the above is done, a VASP will be able to:

[NOTE]
include::partial$treeline-warning.adoc